services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3001:3001"
    environment:
      - THEBEST_API_KEY=${THEBEST_API_KEY}
    restart: unless-stopped
